export const apiKey = 'd6ceab5643f341aaa32224029240701';

export const weatherImages = {
    'Partly cloudy': require('../assets/images/partlycloudy.png'),
    'Moderate rain': require('../assets/images/moderaterain.png'),
    'Patchy rain possible': require('../assets/images/moderaterain.png'),
    'Sunny': require('../assets/images/sun.png'),
    'Clear': require('../assets/images/sun.png'),
    'Overcast': require('../assets/images/cloud.png'),
    'Cloudy': require('../assets/images/cloud.png'),
    'Light rain': require('../assets/images/moderaterain.png'),
    'Moderate rain at times': require('../assets/images/moderaterain.png'),
    'Heavy rain': require('../assets/images/heavyrain.png'),
    'Heavy rain at times': require('../assets/images/heavyrain.png'),
    'Moderate or heavy freezing rain': require('../assets/images/heavyrain.png'),
    'Moderate or heavy rain shower': require('../assets/images/heavyrain.png'),
    'Moderate or heavy rain with thunder': require('../assets/images/heavyrain.png'),
    'Light freezing rain': require('../assets/images/Light freezing rain.png'),
    'Fog': require('../assets/images/fog.png'),
    'Light snow': require('../assets/images/Light snow.png'),
    'Heavy snow': require('../assets/images/Heavy snow.png'),
    'Moderate snow': require('../assets/images/Moderate snow.png'),
    'Freezing fog': require('../assets/images/Freezing fog.png'),
    'Patchy snow possible': require('../assets/images/Patchy snow possible.png'),
    'Mist': require('../assets/images/mist.png'),
    'Patchy sleet possible':require('../assets/images/Patchy sleet possible.png'),
    'Patchy freezing drizzle possible':require('../assets/images/Patchy freezing drizzle possible.png'),
    'Thundery outbreaks possible':require('../assets/images/Thundery outbreaks possible.png'),
    'Blowing snow':require('../assets/images/Blowing snow.png'),
    'Blizzard':require('../assets/images/Blizzard.png'),
    'Patchy light drizzle':require('../assets/images/Patchy light drizzle.png'),
    'Light drizzle':require('../assets/images/Light drizzle.png'),
    'Freezing drizzle':require('../assets/images/Freezing drizzle.png'),
    'Heavy freezing drizzle':require('../assets/images/Heavy freezing drizzle.png'),
    'Patchy light rain':require('../assets/images/Patchy light rain.png'),
    'Light sleet':require('../assets/images/Light sleet.png'),
    'Moderate or heavy sleet':require('../assets/images/Moderate or heavy sleet.png'),
    'Patchy light snow':require('../assets/images/Patchy light snow.png'),
    'Patchy moderate snow':require('../assets/images/Patchy moderate snow.png'),
    'Patchy heavy snow':require('../assets/images/Patchy heavy snow.png'),
    'Ice pellets':require('../assets/images/Ice pellets.png'),
    'Light rain shower':require('../assets/images/Light rain shower.png'),
    'Torrential rain shower':require('../assets/images/Torrential rain shower.png'),
    'Light sleet showers':require('../assets/images/Light sleet showers.png'),
    'Moderate or heavy sleet showers':require('../assets/images/Moderate or heavy sleet showers.png'),
    'Light snow showers':require('../assets/images/Light snow showers.png'),
    'Moderate or heavy snow showers':require('../assets/images/Moderate or heavy snow showers.png'),
    'Light showers of ice pellets':require('../assets/images/Light showers of ice pellets.png'),
    'Moderate or heavy showers of ice pellets':require('../assets/images/Moderate or heavy showers of ice pellets.png'),
    'Patchy light rain with thunder':require('../assets/images/Patchy light rain with thunder.png'),
    'Patchy light snow with thunder':require('../assets/images/Patchy light snow with thunder.png'),
    'Moderate or heavy snow with thunder':require('../assets/images/Moderate or heavy snow with thunder.png'),
    'other': require('../assets/images/moderaterain.png')
  };
